
#ddev-generated
# You can copy this Dockerfile.example to Dockerfile to add configuration
# or packages or anything else to your webimage
# These additions will be appended last to ddev's own Dockerfile

COPY install_zephir.sh /var/tmp/
RUN /bin/bash /var/tmp/install_zephir.sh
